language: ruby
rvm:
- 2.6
- 2.5
# - jruby-head

sudo: false
cache: bundler

before_install: gem install bundler
script: bundle exec rspec spec

jobs:
  include:
    - rvm: jruby-head
      before_install: gem install bundler -v 2.1.4

notifications:
  email:
  - sebastien@prismic.io

deploy:
  provider: rubygems
  api_key:
    secure: TBCtAi8FnlHzuiv86Me/YpMdGeAiG9d+J3ZpxWIY32jJv+t8dsW8Fej4jhGSW0aarPT7sarXan6cez0ssSDObUwWMYJfshmMsKykTi6TW4US2ZXtWxtglABYK2DJ/8N1fgkdXKO0NRMF7RVUoJNSw+91GX7ug/obNiCcmG/ms5I=
  gemspec: prismic.gemspec
  on:
    tags: true
    all_branches: true
