language: ruby
rvm:
#- ruby-head
- 2.6.3
- 2.5.5
- 2.4.6
- jruby-head
- jruby-9.1.9.0
#- jruby-1.7.26

sudo: false
cache: bundler

before_install: gem install bundler:1.16.0
script: bundle exec rspec spec

notifications:
  email:
  - sebastien@prismic.io

deploy:
  provider: rubygems
  api_key:
    secure: TBCtAi8FnlHzuiv86Me/YpMdGeAiG9d+J3ZpxWIY32jJv+t8dsW8Fej4jhGSW0aarPT7sarXan6cez0ssSDObUwWMYJfshmMsKykTi6TW4US2ZXtWxtglABYK2DJ/8N1fgkdXKO0NRMF7RVUoJNSw+91GX7ug/obNiCcmG/ms5I=
  gemspec: prismic.gemspec
  on:
    tags: true
    all_branches: true
